baseURL: "https://durianc.github.io/"
title: Weiyu Chen
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags


params:
    description: "This website hosts Weiyu Chen's education information, research projects, papers, intern experiences, skills, and interests."
    author: Weiyu Chen
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Weiyu Chen
          subtitle: "MSc student at the University of Hong Kong working on embodied AI and multimodal large models. My interests include causal world models, vision–language–action (VLA) systems, visual understanding, and knowledge-enhanced large models such as retrieval-augmented generation (RAG)."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: About
              url: about/
            - name: Education
              url: education/
            - name: Publications
              url: publications/
            - name: Projects
              url: projects/
            - name: Internship
              url: internship/
            - name: Skills
              url: skills/

    socialIcons:
          - name: Email
            url: contact/
          - name: Google Scholar
            url: https://scholar.google.com/citations?user=9Aq6J7IAAAAJ

          - name: ORCID
            url: https://orcid.org/0009-0002-5245-762X

          - name: OpenReview
            url: https://openreview.net/profile?id=%7EWeiyu_Chen4

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Weiyu Chen"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2